package com.astraedus.nudge.ui.localization

import android.content.res.Resources
import com.astraedus.nudge.R

/** Localizes app-owned labels emitted by pure models. Never apply to user text or app names. */
fun Resources.builtInCopy(value: String): String = builtInResources[value]?.let(::getString) ?: value

/** Formatter injected into pure summary/import builders; arguments may contain user data. */
fun Resources.formatCopy(template: String, args: List<Any>): String =
    pluralResources[template]?.let { getQuantityString(it, (args.first() as Number).toInt(), *args.toTypedArray()) }
        ?: builtInResources[template]?.let { getString(it, *args.toTypedArray()) }
        ?: if (args.isEmpty()) builtInCopy(template) else String.format(java.util.Locale.getDefault(), template, *args.toTypedArray())

private val pluralResources = mapOf(
    "Import %1\$s rule(s)" to R.plurals.import_rule_count,
    " and %1\$s group(s)" to R.plurals.import_group_count,
    "\n\nIncludes %1\$s history event(s) (%2\$s new)." to R.plurals.import_history_count,
    "Imported: %1\$s rule(s)" to R.plurals.imported_rule_count,
)

private val builtInResources = mapOf(
    "Language" to R.string.language_title,
    "System default" to R.string.language_system,
    "Hard Block" to R.string.mode_hard_block,
    "Delay" to R.string.mode_delay,
    "Hold" to R.string.mode_hold,
    "Breathing" to R.string.mode_breathing,
    "Other" to R.string.mode_other,
    "Inherit" to R.string.mode_inherit,
    "Block" to R.string.mode_block,
    "Not blocked." to R.string.mode_none_description,
    "Completely blocks the app. You can only go back to the home screen." to R.string.mode_hard_description,
    "Shows a countdown timer before letting you in. Gives you time to reconsider." to R.string.mode_delay_description,
    "You hold a button for the whole wait. Let go and it starts over." to R.string.mode_hold_description,
    "Guides you through a breathing exercise before opening. Calms the impulse." to R.string.mode_breathing_description,
    "Strict Mode locked" to R.string.strict_locked,
    "Unlock" to R.string.unlock,
    "Turn off Strict Mode" to R.string.turn_off_strict,
    "Turn on the daily 2-minute pass" to R.string.turn_on_pass,
    "Turn off all blocking" to R.string.turn_off_blocking,
    "Weaken blocking for this app" to R.string.weaken_app,
    "Delete blocking for this app" to R.string.delete_app_blocking,
    "Disable blocking for this app" to R.string.disable_app_blocking,
    "Take this app off your Nuke list" to R.string.remove_nuke_app,
    "End Nuke without your code" to R.string.end_nuke_without_code,
    "Replace your Nuke code" to R.string.replace_nuke_code,
    "Remove your Nuke code" to R.string.remove_nuke_code,
    "Nuke code removed." to R.string.nuke_code_removed,
    "That's not your Nuke code." to R.string.nuke_wrong_code,
    "That's not the code on screen. Scan the one you just saved." to R.string.nuke_wrong_saved,
    "Nuke is on." to R.string.nuke_armed,
    "Nuke is off." to R.string.nuke_disarmed,
    "Add at least one app to your Nuke list first." to R.string.nuke_empty_list,
    "Paired. Keep that code somewhere inconvenient." to R.string.nuke_paired,
    "Nuke is on, and this screen is a way around it. Type the code to change Nudge's system settings, or go back." to R.string.strict_guard_nuke,
    "Strict Mode is protecting this screen. Unlock to change Nudge's system settings, or go back." to R.string.strict_guard,
    "Launcher does not support pinning" to R.string.launcher_pin_unavailable,
    "Couldn't save the QR image to share" to R.string.qr_share_failed,
    "No app available to share with" to R.string.qr_no_share_app,
    "Couldn't open the camera" to R.string.camera_open_failed,
    "Open Settings > Apps > Nudge > Permissions" to R.string.camera_settings_hint,
    "Could not read that file." to R.string.backup_read_failed,
    "Import settings that reduce protection" to R.string.backup_weaken,
    "Backup saved. It holds your rules, your history and your app settings." to R.string.backup_saved,
    "Could not write the backup there. Try again, or pick a different folder." to R.string.backup_write_failed,
    "Websites" to R.string.websites,
    "Feed" to R.string.feed,
    "Not blocked" to R.string.not_blocked,
    "Whole app" to R.string.whole_app,
    "Scheduled" to R.string.scheduled,
    "Counter" to R.string.counter,
    "Configured" to R.string.configured,
    "Time remaining" to R.string.time_remaining,
    "Yesterday" to R.string.yesterday,
    "This wk" to R.string.this_week,
    "%1\$s wk ago" to R.string.weeks_ago,
    "%1\$s:00" to R.string.hour_label,
    "%1\$s %2\$s s" to R.string.mode_duration,
    "%1\$s min/day" to R.string.rule_daily_limit,
    "Auto-kick@%1\$s" to R.string.rule_kick_interactions,
    "Auto-kick@%1\$s min" to R.string.rule_kick_minutes,
    "%1\$s: %2\$s blocks" to R.string.weekday_blocks,
    "Nudge is off" to R.string.monitor_off,
    "Nudge is not blocking" to R.string.monitor_not_blocking,
    "Nudge is active" to R.string.monitor_active,
    "Blocking is turned off" to R.string.monitor_blocking_off,
    "Blocking is on" to R.string.monitor_blocking_on,
    "Accessibility access is off. Tap to turn it on." to R.string.monitor_access_off,
    "Your phone stopped Nudge. Tap to turn accessibility off and on again." to R.string.monitor_stopped,
    "Blocked by Nudge" to R.string.cover_blocked,
    "%1\$s blocked by Nudge" to R.string.cover_feature_blocked,
    "Today: %1\$s" to R.string.counter_today,
    "taps" to R.string.counter_taps,
    "scrolls" to R.string.counter_scrolls,
    "app" to R.string.counter_app,
    "web" to R.string.counter_web,
    "%1\$s h" to R.string.duration_hour,
    "%1\$s min" to R.string.duration_minute,
    "%1\$s s" to R.string.duration_second,
    "< 1 min" to R.string.duration_under_minute,
    "%1\$s left" to R.string.duration_left,
    "Auto-kick cooldown" to R.string.auto_kick_cooldown,
    "Auto-kick cooldown — %1\$s" to R.string.web_auto_kick_cooldown,
    "Import %1\$s rule(s)" to R.string.import_rules,
    " and %1\$s group(s)" to R.string.import_groups,
    "?\n\nDuplicate rules will be skipped." to R.string.import_duplicates_note,
    "\n\nIncludes %1\$s history event(s) (%2\$s new)." to R.string.import_history,
    " and will be left out:" to R.string.import_left_out,
    "\n\nAlso restores app settings, replacing this device's." to R.string.import_replace_settings,
    "Imported: %1\$s rule(s)" to R.string.imported_rules,
    "\nGroups created: %1\$s" to R.string.imported_groups,
    "\nSkipped (duplicates): %1\$s" to R.string.imported_duplicates,
    "\n\nHistory events restored: %1\$s" to R.string.imported_history,
    "\nHistory already present: %1\$s" to R.string.imported_history_duplicates,
    "\nHistory could not be read: %1\$s" to R.string.imported_history_invalid,
    "\n\nApp settings restored" to R.string.imported_settings,
    "\nSettings that could not be read: %1\$s" to R.string.imported_settings_invalid,
    "\n\nSkipped (could not be read): %1\$s" to R.string.imported_invalid,
    "\n• ...and %1\$s more" to R.string.import_more_reasons,
    "1 entry could not be read" to R.string.import_one_invalid,
    "%1\$s entries could not be read" to R.string.import_many_invalid,
    "1 history event could not be read" to R.string.import_one_history_invalid,
    "%1\$s history events could not be read" to R.string.import_many_history_invalid,
    "1 setting could not be read" to R.string.import_one_setting_invalid,
    "%1\$s settings could not be read" to R.string.import_many_settings_invalid,
    "Invalid or missing version field" to R.string.error_version_missing,
    "Export version %1\$s is newer than supported (%2\$s). Please update the app." to R.string.error_version_newer,
    "Invalid JSON format: %1\$s" to R.string.error_invalid_json,
    "Invalid data: %1\$s" to R.string.error_invalid_data,
    "No valid rules or groups found. All %1\$s entries were invalid:" to R.string.error_no_valid,
    "...and %1\$s more" to R.string.error_more,
    "%1\$s %2\$s: %3\$s" to R.string.error_entry,
    "Rule" to R.string.error_rule,
    "Group" to R.string.error_group,
    "History event" to R.string.error_history,
    "Setting %1\$s: %2\$s" to R.string.error_setting,
    "could not be read" to R.string.error_unreadable,
    "Unknown block mode: %1\$s" to R.string.error_unknown_mode,
    "Challenge length %1\$s is outside 1..%2\$s" to R.string.error_challenge_range,
    "Package name is blank" to R.string.error_package_blank,
    "Group name is blank" to R.string.error_group_blank,
    "Timestamp is not a positive epoch-millisecond value" to R.string.error_timestamp,
    "%1\$s is missing or is not text" to R.string.error_missing_text,
    "%1\$s is missing or is not a number" to R.string.error_missing_number,
    "%1\$s %2\$s" to R.string.error_field_type,
    "is not true or false" to R.string.error_not_boolean,
    "is not text" to R.string.error_not_text,
    "is not a number" to R.string.error_not_number,
    "must be an array" to R.string.error_not_array,
    "must be an object" to R.string.error_not_object,
    "Off" to R.string.ui_off,
    "Cancel" to R.string.ui_cancel,
    "Today" to R.string.ui_today,
    "Last 7 days" to R.string.ui_last_7_days,
    "Hold Duration" to R.string.ui_hold_duration,
    "Delay Duration" to R.string.ui_delay_duration,
    "End Nuke" to R.string.ui_end_nuke,
    "Pair a Nuke code first." to R.string.ui_pair_a_nuke_code_first,
    "Grayscale" to R.string.ui_grayscale,
    "No blocks yet in this period" to R.string.ui_no_blocks_yet_in_this_period,
    "No data in this period" to R.string.ui_no_data_in_this_period,
    "Explore" to R.string.ui_explore,
    "7 days" to R.string.ui_7_days,
    "30 days" to R.string.ui_30_days,
    "Share backup" to R.string.ui_share_backup,
    "Mon" to R.string.ui_mon,
    "Tue" to R.string.ui_tue,
    "Wed" to R.string.ui_wed,
    "Thu" to R.string.ui_thu,
    "Fri" to R.string.ui_fri,
    "Sat" to R.string.ui_sat,
    "Sun" to R.string.ui_sun,
    "Hard block" to R.string.mode_hard_block,
)
